### ISSUE TITLE
Bottomless badge does nothing

### ISSUE THREAD

**Issue by EmilyEmmi** [rovertronic/Mario-Builder-64#10]
The bottomless badge description reads:
"Uses 1 mana instead of 1/3 HP when falling off the level."
However, neither of these features appear to be present, and falling off the level will still instantly kill Mario no matter what.

Edit: Gonna tack on a really minor visual thing I just found related to badges. Getting a burden badge in water has Mario still do the "star get" animation, unlike on land where he does the death animation instead.

**Comment by rovertronic** [comment]
Working on this 👍
