### ISSUE TITLE
Error on Project64

### ISSUE THREAD

**Issue by chinnestchin** [rovertronic/Mario-Builder-64#12]
When i play it on Project64, it says Fatal Error: Stopping Emulation and nothing else.
![Ekran görüntüsü 2024-05-22 194051](https://github.com/rovertronic/Mario-Builder-64/assets/166732054/83c187d9-be2a-4c6c-8ebf-86da582ce1e1)

**Comment by KingMonkeyBug** [comment]
Just use parallel launcher.
