### ISSUE TITLE
Map causes freeze

### ISSUE THREAD

**Issue by niansa** [rovertronic/Mario-Builder-64#16]
This map I have created (just been messing around) causes the game to crash reliably: [12.mb64](https://github.com/rovertronic/Mario-Builder-64/files/15439655/12.mb64.zip)

I am not sure what it is about the map that causes this issue. To reproduce, just enter the map and either touch one of the crystals or just wait for a couple of seconds.

**Comment by SynicalMX** [comment]
Just a theory, but I looked at the map and it seems the bobombs inside the pillar are causing the issue. Everytime one explodes, it has to create a coin, explosion particle, and set a respawn timer for each bobomb. So with the amount of bobombs exploding at once, the game probably just gave up. Just by removing some of the bobombs the game ran fine.

**Comment by niansa** [comment]
Interesting. It only started after I added the crystals, afaIr.
