### ISSUE TITLE
crash when switching from lakitu cam to mario cam while on a pole

### ISSUE THREAD

**Issue by toolateralus** [rovertronic/Mario-Builder-64#19]
The map I experience the bug on : https://levelsharesquare.com/levels/6655e45914269c86dfd67d0d#!
(when I made this issue I didn't know I could just zip the .mb64 and attach it, sorry)

I haven't been able to reproduce it anywhere else. 

#### producing the bug
- this only happens in the `Play` mode
- simply climb up the level (2 floors from start) and grab the pole while in lakitu camera.
switch to mario cam: you get this exception.

note: I'm on the latest linux mint, if that matters at all.

![exception0](https://github.com/rovertronic/Mario-Builder-64/assets/109556963/14fa7e08-22b3-461d-8ef6-76ab0143d51b)
![exception1](https://github.com/rovertronic/Mario-Builder-64/assets/109556963/4bf0d7ba-aea3-4fbe-9144-49508938efd7)

**Comment by Cloneian28** [comment]
Had the same thing happen to me while testing a level I made
![pressed r on a pole, bad things happened](https://github.com/rovertronic/Mario-Builder-64/assets/69398829/e49289b2-506e-47bc-8233-d44039aca9d3)
Just switching to mario cam while on a pole doesnt seem to replicate it though, so maybe its something else that causes it

**Comment by toolateralus** [comment]
@Cloneian28 did you have fire spitters near the pole? coin lines? that's all I had object-wise.

**Comment by Cloneian28** [comment]
> @Cloneian28 did you have fire spitters near the pole? coin lines? that's all I had object-wise.

I had coins near the pole
and i just managed to replicate it on video, it looks like it happens when you switch to mario cam on the first few frames of grabbing the pole

https://github.com/rovertronic/Mario-Builder-64/assets/69398829/47b4a6a4-f866-40c2-a1c2-4b6ccfb25e84

**Comment by rovertronic** [comment]
It's already fixed in the dev branch. It will be shipped with the 1.1 update.
