### ISSUE TITLE
Level list is empty after selecting "Save & Quit" option from level editor

### ISSUE THREAD

**Issue by Polprzewodnikowy** [rovertronic/Mario-Builder-64#2]
Steps to reproduce:
1. Run ROM
2. Start building new level
3. Add some blocks
4. Open level settings
5. Navigate to system tab
6. Select "Save & Quit"
7. Message pops up: "No levels currently loaded yet."

Expected outcome:
After save & quit I should see last saved level in the list

Environment:
NTSC N64 console with SummerCart64 flashcart and exFAT file system on the SD card

**Comment by Polprzewodnikowy** [comment]
I've submitted a fix here: https://github.com/rovertronic/Mario-Builder-64/pull/13

**Comment by rovertronic** [comment]
Thank you! I'll merge this in a bit. Out of curiosity, why does using chdir cause problems on flashcarts? I'd like to know for future reference.

**Comment by Polprzewodnikowy** [comment]
Main issues seems to be stemming from:
1. No error checking. Didn't find the exact function that causes chdir to fail, but `f_opendir` in `load_level_files_from_sd_card` function returns `FR_NO_PATH` so somewhere the path is getting desynced. I've tried to use `f_getcwd` to look what's going on but it just returned empty string, which should mean root directory.
2. Incorrect usage of pointers. In many places level directory string was incorrectly passed to the function. Since string already is a pointer, there's no need to add `&` to get the address. Compiler warnings are very clear about that.
![image](https://github.com/rovertronic/Mario-Builder-64/assets/3756990/12b281f4-ae9f-43a1-af9a-5eac2ec2318d)
![image](https://github.com/rovertronic/Mario-Builder-64/assets/3756990/08022ea6-c195-4723-97b1-6613f40b4e3f)

As of why this works in the Parallel launcher and not on the real hardware, my assumption is just inaccurate emulation. Maybe there's some place where cache coherency is not taken care of - emulators usually don't implement CPU cache correctly.

If you want to keep `f_chdir` then quick fix seems to be to always chdir into absolute path (add `/` at the beginning):
![Screenshot 2024-05-23 105538](https://github.com/rovertronic/Mario-Builder-64/assets/3756990/85d47285-c893-4966-ac46-92eb0cbbfdf4)
But I strongly recommend just sticking to the absolute paths. Doing `f_chdir` in random places is error prone and confusing to the uninitiated reader.
