### ISSUE TITLE
Feature request: PC port

### ISSUE THREAD

**Issue by Cloudef** [rovertronic/Mario-Builder-64#24]
Having ability to compile for PC would be neat

**Comment by AgentXLP** [comment]
![image](https://github.com/rovertronic/Mario-Builder-64/assets/44549182/7b24ffc1-2cd3-4e9c-ad6b-0df42e12fa1f)

**Comment by Tycho10101** [comment]
I thought this too!

**Comment by dave41413** [comment]
maybe someone will one day

i wonder if we could just paste code in, probably not

**Comment by Mariosonicman91** [comment]
Pretty sure he said HE wouldn't do this, but wouldn't stop anyone else who will.
