### ISSUE TITLE
Crash while playing "Big Duds Factory"

### ISSUE THREAD

**Issue by Stevoisiak** [rovertronic/Mario-Builder-64#27]
### Summary

I encountered a game crash while playing the level [Big Duds Factory](https://levelsharesquare.com/levels/664f5e3f3e9df714e5c6922b).

### Screenshot/Video

![vlcsnap-2024-06-15-19h56m52s907](https://github.com/rovertronic/Mario-Builder-64/assets/1330770/9a4d8e4b-ecdd-4878-ad75-d9a53a6a5c9e)

https://youtu.be/fvAo0KwaWVI?t=511

Crash occurs at 8:43

### System Specs
- System: Valve Steam Deck 512GB LCD
- Game: mb64_v1_0_0.bps
- Emulator: Parallel Launcher v7.7.0

### Extra Details
- The area where the crash happened had slowdown
- Crash occurred right as Mario grabbed a pole
- I have played this level before and this area did not crash on previous playthroughs.

**Comment by couchpotato261** [comment]
I've bumped into this exact bug in other levels; this isn't unique to Big Duds Factory.  Mario Builder 64 crashes when the player goes into Mario camera while on a pole or grabs a pole while in Mario camera.  I posted a new ticket on this issue right before I saw your own post.
