### ISSUE TITLE
Bug: Periods in filename cut off stage titles

### ISSUE THREAD

**Issue by Stevoisiak** [rovertronic/Mario-Builder-64#28]
### Summary
If a stage's filename has a period in it, such as "[Rex Rusty Ruins (v.2)](https://levelsharesquare.com/levels/6656f64014269c86dfe71482)", the name will be cut off on the level's pause screen, ie: "Rex Rusty Ruins (v"

### Screenshots
![20240616075433_1](https://github.com/rovertronic/Mario-Builder-64/assets/1330770/f0184441-366d-4d2e-b8fa-da2ec79fb4e9)

![20240616075442_1](https://github.com/rovertronic/Mario-Builder-64/assets/1330770/deb2e03f-64ce-44ff-a117-78e41f965e2a)

**Comment by dave41413** [comment]
probably screen or name limitaetions

**Comment by dave41413** [comment]
also why green mario

**Comment by Stevoisiak** [comment]
> probably screen or name limitaetions

I'd assume it's because periods usually can't be entered in a level name.

> also why green mario

That's just part of the linked level.
