### ISSUE TITLE
Koopa the quick gets stuck in the jumping animation when jumping into the water

### ISSUE THREAD

**Issue by GrubPL** [rovertronic/Mario-Builder-64#3]
So i was makin a level  and i encountered the issue of Koopa the quick's animation just being stuck in the jump animation after jumping into water, not much i can say, other than im using the paraller launcher with default settings, i dont think ill need to give more info

**Comment by KingMonkeyBug** [comment]
We as the creators and the players would really need this fix!

**Comment by Mariosonicman91** [comment]
Koopa the Quick in general is too hard to work with without setting a path designed with him in mind or making him cheat up a wall. I want his jumps to be bigger! :D

**Comment by GrubPL** [comment]
> Koopa the Quick in general is too hard to work with without setting a path designed with him in mind or making him cheat up a wall. I want his jumps to be bigger! :D

Ok but what does it have to do with my issue

**Comment by Mariosonicman91** [comment]
Additions
