### ISSUE TITLE
Feature Request: Way to make slopes fit in gaps.

### ISSUE THREAD

**Issue by BeezBumba** [rovertronic/Mario-Builder-64#36]
It's hard to describe just look at the image. 
![Screenshot 2024-06-28 082158](https://github.com/rovertronic/Mario-Builder-64/assets/130922034/fae2373f-8f20-40ac-b514-2e3f4b0d70fa) I can't put the lower and upper gentle slopes, because there are already upside down slopes.

**Comment by Mariosonicman91** [comment]
Block combos, huh?
This could be added, as long as the blocks FIT.
Being able to just randomly add blocks together shouldn't be possible tho.

**Comment by Mariosonicman91** [comment]
Also nice 3DW Captain Toad 1-1 Recreation!

**Comment by BeezBumba** [comment]
I just use lower gentle slopes and upper gentle slopes. What I'm saying is to add a way to put slopes in the same grid square.

**Comment by Mariosonicman91** [comment]
Yeah, that's exactly what I'm saying, just possible with more block variants.
