### ISSUE TITLE
Game crash with poles/trees & Mario camera

### ISSUE THREAD

**Issue by couchpotato261** [rovertronic/Mario-Builder-64#42]
Mario Builder 64 crashes if I switch to Mario camera while climbing a tree or pole, and it also crashes if I grab a tree or pole while in Mario camera.  Lakitu camera doesn't cause any problems though.

**Comment by couchpotato261** [comment]
I'd post this issue on Rovertronic's Discord server also, but I don't have permission (at the time of this post) to write any messages on the server.

**Comment by couchpotato261** [comment]
By the way, Stevoisiak also reported on this bug with "Crash while playing 'Big Duds Factory.'"

**Comment by BeezBumba** [comment]
> I'd post this issue on Rovertronic's Discord server also, but I don't have permission (at the time of this post) to write any messages on the server.

the server does not need phone number anymore just so you know.
