### ISSUE TITLE
Bug: Certain special characters make level titles UPPERCASE, trimmed, and spaceless

### ISSUE THREAD

**Issue by Stevoisiak** [rovertronic/Mario-Builder-64#53]
Levels that use certain special characters like é in their name cause the title display to break. For example:

-  Vine Vinéyard.mb64 = VINEVI01.MB6
- ✨💫 Astro Views.mb64 = ASTROV01.MB6
- ✦ Space Slide ✦.mb64 = SPACES01.MB6

### Steps to reproduce
1. Create and save a level.
2. Open SD card and find the level file.
3. Rename level filename to include é
4. Open Mario Builder and find level in the level list.

### Screenshot

![image](https://github.com/user-attachments/assets/cb6e0427-e73f-40d0-be12-4172cc330b56)

**Comment by Mariosonicman91** [comment]
You're not supposed to input those special characters, as they are unavailable through the game's hud.
You're editing the game files and claiming there's a bug due to an unintended behavior caused by yourself.

**Comment by Stevoisiak** [comment]
> You're not supposed to input those special characters, as they are unavailable through the game's hud. You're editing the game files and claiming there's a bug due to an unintended behavior caused by yourself.

These are level files I've been downloading from Level Share Square and the Rovertronic Discord, officially supported sources. Renaming level files is also the only way to rename a level after it's been made.
